### ISSUE TITLE
Null pointer spam for days.

### ISSUE THREAD

**Issue by Darkmega18** [mraof/Minestuck#170]
Just got off my server made with mainly minestuck in mind, however, in my MC console I'm just drowning in apparent "fatal" errors which happen to be null pointers.

17:34:04 | net.minecraft.client.Minecraft | Error executing task java.util.concurrent.ExecutionException: java.lang.NullPointerException 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.NullPointerException
-- | -- | --

like such. only...
![console is already dead](https://user-images.githubusercontent.com/8104689/42367031-2b4d4496-8146-11e8-9e9c-1f6016f19521.png)
theres thousands of them apparently. I've been in the medium the entire time doing base stuff and fighting imps etc over the last few hours.

only other big mods are tinkers, cyclic, and quark. then theres JEI etc and a few other smaller things.

**Comment by BenjaminKirksey** [comment]
So I just want to confirm a few things:
1) When do these messages appear? Do they appear when you are in the Medium, when anyone is in the Medium, when you're in your Land, when anyone is in your Land, always, or what?
2) What kind of Lands have been loaded (i.e. had at least one player in them) when these messages were appearing?

**Comment by Darkmega18** [comment]
in the console just gradually while I'm in the medium. friend is also in the medium and they seem to continue popping in while there too.

**Comment by Darkmega18** [comment]
oh, sorry. I was the sylph of light in the land of light and snow. friend is the witch of space in the land of rock (stone?) and buckets.

I only notice the null build up when I'm tabbing out and stuff. but even when just doing base stuff and working on getting more alchemy patterns and cards cataloged in my chests for later use the nulls will still build up over time.

**Comment by Darkmega18** [comment]
I have discovered that it seems to be building up during my time in build mode. I was in the overworld this time using build mode to sit around in basically creative mode for a while to do some configs while on the server, when I went to check my console and reload the game to refresh the configs I had a whole lot of null pointers of the same type from when I had this on my "Micro pack" just like from playing minestuck with a few other mods.

**Comment by Darkmega18** [comment]
so there should be more? it's not the stuff in between the two messages after error executing task? Since thats all it spits out.

this is what's in my latest log in my larger modpack on curse.

`[01:22:59] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1214) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:54) ~[ih.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:11) ~[ih.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
[01:22:59] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147266_a(NetHandlerPlayClient.java:1142) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketSetSlot.func_148833_a(SourceFile:30) ~[iu.class:?]
	at net.minecraft.network.play.server.SPacketSetSlot.func_148833_a(SourceFile:10) ~[iu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:20) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more`

does that help?

**Comment by kirderf1** [comment]
By the looks of it, the world client-side appears to be null when it tries to update data for a tile entity of some kind. If it's not that, there might be something that has changed the code from what I'm looking at. Are you using any coremods, and what version of forge are you using?

**Comment by Darkmega18** [comment]
I can drop you a full log of some kind the next time I close MC? I know the logs seem to print out a modlist. there are probably a fair few core mods at this point... but heres the list out of the top of one of my recent crash logs of some form.

`  AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd_signed.jar)
  CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.9.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
  AstralCore (astralsorcery-1.12.2-1.9.3.jar)
  HCASM (HammerCore-1.12.2-2.0.0.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  llibrary (llibrary-core-1.0.6-1.12.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.9.jar)
  ObfuscatePlugin (obfuscate-0.2.4-1.12.2.jar)
  ComfortsCoreLoadingPlugin (comforts-1.12.2-1.2.0.jar)`

**Comment by kirderf1** [comment]
At least I was checking with the same forge version.
Alright, I think I'll try to reproduce this thing myself and then pinpoint which of them are involved.

**Comment by kirderf1** [comment]
Nope, did not get anything like that while entering editmode. Do you think you can figure out what's needed in order to replicate it?

**Comment by Darkmega18** [comment]
it's different circumstances each time. but I can send you a twitch profile of my pack, "Transcendence" and you can look over it and potentially come to the server and see if it happens first hand?

cause my first pack that did it only had stuff like cyclic, tinkers, chisel, baubles, furnus, thermal foundation+world (no actual expansion) as big name large mods.

transcendence does have a bit of overlap in that it uses cyclic, furnus chisel and baubles. so those could be potential mods to look closer at. but transcendence has a lot more mods and it still happens. possibly cause of the same reasons the testing pack did.

**Comment by kirderf1** [comment]
Yeah, minestuck has a public discord server. (Though it appears that it's not linked at github, but only on the tumblr page) You should drop by: https://discordapp.com/invite/tEKWvqH

**Comment by kirderf1** [comment]
Anyways, it doesn't seem to be a minestuck issue, so I'll close it here.
